# Generated by Django 3.1.8 on 2021-04-07 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210406_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='_user_contacts_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
