# Generated by Django 3.1.8 on 2021-04-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FIO'),
        ),
    ]
