# Generated by Django 3.1.8 on 2021-05-14 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 0, 20), verbose_name='Expires at'),
        ),
    ]
