# Generated by Django 3.1.7 on 2021-05-26 11:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210519_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='_user_blocked_users_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.BooleanField(default=False, verbose_name='Продавец'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Верифицирован'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 0, 20), verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='', verbose_name='Фото документов')),
                ('verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penging_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'PendingUser',
                'verbose_name_plural': 'PendingUsers',
            },
        ),
    ]
