# Generated by Django 3.1.7 on 2021-05-26 11:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210519_1039'),
    ]

    operations = [

    ]
