# Generated by Django 3.1.7 on 2021-05-28 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210526_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 0, 20), verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
