from django.urls import path
from .views import (
    CategoryListAPI,
    DelieveryChoiceListAPI,
    PaymentChoiceListAPI,
    CardGetAPI,
    CardCreateAPI,
    RateCreateAPI,
    CommentCreateAPI,
    SellersList,
    CardFilteredAPI,
    #! to add
    ShopCommentCreateAPI,
    ShopRateCreateAPI,
    ShopCreateAPI,
    ShopGetAPI,
    ShopPartialUpdateAPI,
    CouponCreateAPI,
    AddressCreateAPI,
    ScheduleCreateAPI,
    OrderItemCreateAPI,
    OrderItemGetAPI,
    OrderItemUpdateAPI,
    OrderItemDeleteAPI,
    OrderCreateAPI,
    OrderGetAPI,
    OrderUpdateAPI,
    ShopDeleteAPI,
    CardLatestAPI,
    UserOrderGetAPI,
    MainSliderListAPI,
)

urlpatterns = [
    path('categories-list/', CategoryListAPI.as_view(), name=''),
    path('main-slider-list/', MainSliderListAPI.as_view(), name=''),
    path('sellers-list/', SellersList.as_view(), name=''),
    path('delivery-list/', DelieveryChoiceListAPI.as_view(), name=''),
    path('payment-list/', PaymentChoiceListAPI.as_view(), name=''),
    path('card-get/<int:pk>', CardGetAPI.as_view(), name=''),
    path('cards-filtered/', CardFilteredAPI.as_view(), name=''),
    path('cards-main-page/', CardLatestAPI.as_view(), name=''),
    path('card-create/', CardCreateAPI.as_view(), name=''),
    path('rate-create/', RateCreateAPI.as_view(), name=''),
    path('comment-create/', CommentCreateAPI.as_view(), name=''),

    path('shop-comment-create/', ShopCommentCreateAPI.as_view(), name=''),
    path('shop-rate-create/', ShopRateCreateAPI.as_view(), name=''),
    path('shop-create/', ShopCreateAPI.as_view(), name=''),
    path('shop-delete/', ShopDeleteAPI.as_view(), name=''),
    path('shop-get/<int:pk>', ShopGetAPI.as_view(), name=''),
    path('shop-partial-update/', ShopPartialUpdateAPI.as_view(), name=''),
    path('coupon-create/', CouponCreateAPI.as_view(), name=''),
    path('address-create/', AddressCreateAPI.as_view(), name=''),
    path('schedule-create/', ScheduleCreateAPI.as_view(), name=''),
    path('order-item-create/', OrderItemCreateAPI.as_view(), name=''),
    path('order-item-delete/', OrderItemDeleteAPI.as_view(), name=''),
    path('order-item-get/<int:pk>', OrderItemGetAPI.as_view(), name=''),
    path('order-item-partial-update/<int:pk>', OrderItemUpdateAPI.as_view(), name=''),
    path('order-create/', OrderCreateAPI.as_view(), name=''),
    path('order-get/', OrderGetAPI.as_view(), name=''),
    path('order-partial-update/', OrderUpdateAPI.as_view(), name=''),
    path('user-orders-get/', UserOrderGetAPI.as_view(), name=''),

]
