from django.urls import path
from .views import (
    CategoryListAPI,
    DelieveryChoiceListAPI,
    PaymentChoiceListAPI,
    CardGetAPI,
    CardCreateAPI,
    RateCreateAPI,
    CommentCreateAPI,
    SellersList,
    CardFilteredAPI,
    #! to add
    ShopCommentCreateAPI,
    ShopRateCreateAPI,
    ShopCreateAPI,
    ShopGetAPI,
    ShopPartialUpdateAPI,
    CouponCreateAPI,
    AddressCreateAPI,
    ScheduleCreateAPI,
    OrderItemCreateAPI,
    OrderItemGetAPI,
    OrderItemUpdateAPI,
    OrderItemDeleteAPI,
    OrderCreateAPI,
    OrderGetAPI,
    OrderUpdateAPI,
    ShopDeleteAPI,
    CardLatestAPI,
    UserOrderGetAPI,
    MainSliderListAPI,
    MainPageAPI,
    UserFavouritesAPI,
    ShopOrderGetAPI,
    SingleOrderGetAPI,
    BrandsListAPI,
    CountryListAPI,
    MarkFavourite,
)

urlpatterns = [
    path('categories-list/', CategoryListAPI.as_view(), name='categories-list'),
    path('brand-list/', BrandsListAPI.as_view(), name='brand-list'),
    path('country-list/', CountryListAPI.as_view(), name='country-list'),
    path('main-slider-list/', MainSliderListAPI.as_view(), name='main-slider'),
    path('main-page/', MainPageAPI.as_view(), name='main-page'),
    path('sellers-list/', SellersList.as_view(), name='sellers-list'),
    path('delivery-list/', DelieveryChoiceListAPI.as_view(), name='delivery-list'),
    path('payment-list/', PaymentChoiceListAPI.as_view(), name='payment-list'),
    path('card-get/<int:pk>', CardGetAPI.as_view(), name='card-get'),
    path('cards-filtered/', CardFilteredAPI.as_view(), name='cards-filtered'),
    path('cards-main-page/', CardLatestAPI.as_view(), name='cards-main'),
    path('card-create/', CardCreateAPI.as_view(), name='card-create'),
    path('rate-create/', RateCreateAPI.as_view(), name='rate-create'),
    path('comment-create/', CommentCreateAPI.as_view(), name='comment-create'),


    path('shop-comment-create/', ShopCommentCreateAPI.as_view(), name='shop-comment'),
    path('shop-rate-create/', ShopRateCreateAPI.as_view(), name='shop-rate'),
    path('shop-create/', ShopCreateAPI.as_view(), name='shop-create'),
    path('shop-delete/', ShopDeleteAPI.as_view(), name='shop-delete'),
    path('shop-get/<int:pk>', ShopGetAPI.as_view(), name='shop-get'),
    path('shop-partial-update/', ShopPartialUpdateAPI.as_view(), name='shop-partial-update'),
    path('coupon-create/', CouponCreateAPI.as_view(), name='coupon-create'),
    path('address-create/', AddressCreateAPI.as_view(), name='address-create'),
    path('schedule-create/', ScheduleCreateAPI.as_view(), name='schedule-create'),
    path('user-favourites/', UserFavouritesAPI.as_view(), name='user-favourites'),
    path('order-item-create/', OrderItemCreateAPI.as_view(), name='order-item-create'),
    path('order-item-delete/', OrderItemDeleteAPI.as_view(), name='order-item-delete'),
    path('order-item-get/<int:pk>', OrderItemGetAPI.as_view(), name='order-item-get'),
    path('order-item-partial-update/<int:pk>', OrderItemUpdateAPI.as_view(), name='order-item'),
    path('order-create/', OrderCreateAPI.as_view(), name='order-create'),
    path('order-get/', OrderGetAPI.as_view(), name='order-get'),
    path('single-order-get/<int:pk>', SingleOrderGetAPI.as_view(), name='single-order-get'),
    path('order-partial-update/', OrderUpdateAPI.as_view(), name='order-partial-update'),
    path('user-orders-get/', UserOrderGetAPI.as_view(), name='user-orders-get'),
    path('shop-orders-get/', ShopOrderGetAPI.as_view(), name='shop-orders-get'),


    path('user-favourites/', UserFavouritesAPI.as_view(), name=''),
    path('mark-favourite/', MarkFavourite.as_view(), name=''),
]
