# Generated by Django 3.1.7 on 2021-06-04 15:38

import apps.utils.func
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import jsonfield.fields
import mptt.fields
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0009_attachment_attachment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelieverChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип доставки')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='PaymentChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип оплаты')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_rate', to=settings.AUTH_USER_MODEL, verbose_name='Оценщик')),
            ],
            options={
                'verbose_name': 'оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('datetime', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, verbose_name='Время комментария')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('display', models.BooleanField(default=True, verbose_name='Отобразить')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('Подкатегория категории', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='shop.category', verbose_name='parent_category')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('present', models.BooleanField(default=True, verbose_name='В наличии')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('discount_price', models.FloatField(default=0, verbose_name='Цена со скидкой')),
                ('preview', imagekit.models.fields.ProcessedImageField(upload_to=apps.utils.func.preview_cards)),
                ('characteristics', jsonfield.fields.JSONField(default=dict, verbose_name='Характеристики')),
                ('attachments', models.ManyToManyField(related_name='card_attachments', to='chat.Attachment', verbose_name='Вложения')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_category', to='shop.category', verbose_name='Категория товара')),
                ('deliver_methods', models.ManyToManyField(related_name='card_deliver_methods', to='shop.DelieverChoice', verbose_name='Способы оплаты')),
                ('payment_methods', models.ManyToManyField(related_name='card_payment_methods', to='shop.PaymentChoice', verbose_name='Способы оплаты')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_creator', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Карточка товара',
                'verbose_name_plural': 'Карточки товаров',
            },
        ),
    ]
