# Generated by Django 3.1.8 on 2021-04-07 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('accepter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposition_chat', to=settings.AUTH_USER_MODEL)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_chat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500, null=True, verbose_name='Message')),
                ('date', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, null=True, verbose_name='Send datetime')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='chat.room', verbose_name='Chat room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_attachment', to='chat.chat')),
            ],
        ),
    ]
