# Generated by Django 3.1.8 on 2021-04-07 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Вложение', 'verbose_name_plural': 'Вложения'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video'), ('audio', 'audio')], default='image', max_length=15, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_attachment', to='chat.chat', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='chat.room', verbose_name='Комната'),
        ),
    ]
