# Generated by Django 3.1.8 on 2021-04-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210407_1519'),
        ('chat', '0002_auto_20210407_1904'),
    ]

    operations = [
    ]
