# Generated by Django 3.1.7 on 2021-05-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210514_0958'),
    ]

    operations = [

        migrations.AlterField(
            model_name='chat',
            name='attachment',
            field=models.ManyToManyField(blank=True, related_name='chat_attachment', to='chat.Attachment'),
        ),
    ]
