# Generated by Django 3.1.7 on 2021-05-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210519_1039'),
    ]

    operations = [
    ]
