# Generated by Django 3.1.7 on 2021-05-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_attachment_attachment_type'),
    ]

    operations = [

    ]
